#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service

PROCESS_NAME="spamlearn-inotify"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting SPAM/HAM Monitor"
python3 /usr/sbin/inotify-spamlearn.py
