#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="spamlearn-inotify"

update_template /usr/sbin/inotify-spamlearn.py SPAMLEARN_CONFIG_FILE

configure_spamlearn_logging
create_spamlearn_configuration

liftoff