#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="rspamd"

check_container_initialized
check_service_initialized init
liftoff

### Set Debug Mode
if var_true "${DEBUG_MODE}" ; then
	debug_arg="--debug"
fi

print_start "Starting rspamd ${RSPAMD_VERSION}"
exec rspamd \
             --user rspamd \
             --group rspamd \
             --no-fork \
             ${debug_arg} \
             DBDIR=${RSPAMD_DATA_LOCATION}
