#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-rspamd ]; then

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
	set -x
	DEBUG_ARG="--debug" 
fi
  echo 'Initialization Complete' >/tmp/state/10-rspamd
fi

echo ''
echo '** Starting rspamd'
exec rspamd --user rspamd --group rspamd --no-fork $DEBUG_ARG
